apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-quota-operator-manager-role
rules:
- apiGroups:
  - gpuquota.example.com
  resources:
  - gpuquotas
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - gpuquota.example.com
  resources:
  - gpuquotas/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - gpuquota.example.com
  resources:
  - gpuquotas/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - jobset.x-k8s.io
  resources:
  - jobsets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  verbs:
  - get
  - list
  - watch
  - update
  - patch
