//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnforcedResource) DeepCopyInto(out *EnforcedResource) {
	*out = *in
	in.EnforcedAt.DeepCopyInto(&out.EnforcedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnforcedResource.
func (in *EnforcedResource) DeepCopy() *EnforcedResource {
	if in == nil {
		return nil
	}
	out := new(EnforcedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUTypeUsage) DeepCopyInto(out *GPUTypeUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUTypeUsage.
func (in *GPUTypeUsage) DeepCopy() *GPUTypeUsage {
	if in == nil {
		return nil
	}
	out := new(GPUTypeUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuBudget) DeepCopyInto(out *GpuBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuBudget.
func (in *GpuBudget) DeepCopy() *GpuBudget {
	if in == nil {
		return nil
	}
	out := new(GpuBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuBudgetList) DeepCopyInto(out *GpuBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GpuBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuBudgetList.
func (in *GpuBudgetList) DeepCopy() *GpuBudgetList {
	if in == nil {
		return nil
	}
	out := new(GpuBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuBudgetSpec) DeepCopyInto(out *GpuBudgetSpec) {
	*out = *in
	if in.GPUHoursLimit != nil {
		in, out := &in.GPUHoursLimit, &out.GPUHoursLimit
		*out = new(float64)
		**out = **in
	}
	if in.DollarsLimit != nil {
		in, out := &in.DollarsLimit, &out.DollarsLimit
		*out = new(float64)
		**out = **in
	}
	out.CheckInterval = in.CheckInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuBudgetSpec.
func (in *GpuBudgetSpec) DeepCopy() *GpuBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(GpuBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuBudgetStatus) DeepCopyInto(out *GpuBudgetStatus) {
	*out = *in
	if in.CurrentPeriodStart != nil {
		in, out := &in.CurrentPeriodStart, &out.CurrentPeriodStart
		*out = (*in).DeepCopy()
	}
	if in.GPUHoursByType != nil {
		in, out := &in.GPUHoursByType, &out.GPUHoursByType
		*out = make([]GPUTypeUsage, len(*in))
		copy(*out, *in)
	}
	if in.LastCheckedTime != nil {
		in, out := &in.LastCheckedTime, &out.LastCheckedTime
		*out = (*in).DeepCopy()
	}
	if in.LastEnforcementTime != nil {
		in, out := &in.LastEnforcementTime, &out.LastEnforcementTime
		*out = (*in).DeepCopy()
	}
	if in.EnforcedResources != nil {
		in, out := &in.EnforcedResources, &out.EnforcedResources
		*out = make([]EnforcedResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuBudgetStatus.
func (in *GpuBudgetStatus) DeepCopy() *GpuBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(GpuBudgetStatus)
	in.DeepCopyInto(out)
	return out
}
