//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnforcedResource) DeepCopyInto(out *EnforcedResource) {
	*out = *in
	in.EnforcedAt.DeepCopyInto(&out.EnforcedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnforcedResource.
func (in *EnforcedResource) DeepCopy() *EnforcedResource {
	if in == nil {
		return nil
	}
	out := new(EnforcedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuQuota) DeepCopyInto(out *GpuQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuQuota.
func (in *GpuQuota) DeepCopy() *GpuQuota {
	if in == nil {
		return nil
	}
	out := new(GpuQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuQuotaList) DeepCopyInto(out *GpuQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GpuQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuQuotaList.
func (in *GpuQuotaList) DeepCopy() *GpuQuotaList {
	if in == nil {
		return nil
	}
	out := new(GpuQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuQuotaSpec) DeepCopyInto(out *GpuQuotaSpec) {
	*out = *in
	out.CheckInterval = in.CheckInterval
	out.GracePeriod = in.GracePeriod
	out.CooldownPeriod = in.CooldownPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuQuotaSpec.
func (in *GpuQuotaSpec) DeepCopy() *GpuQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(GpuQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuQuotaStatus) DeepCopyInto(out *GpuQuotaStatus) {
	*out = *in
	if in.FirstViolationTime != nil {
		in, out := &in.FirstViolationTime, &out.FirstViolationTime
		*out = (*in).DeepCopy()
	}
	if in.LastCheckedTime != nil {
		in, out := &in.LastCheckedTime, &out.LastCheckedTime
		*out = (*in).DeepCopy()
	}
	if in.LastEnforcementTime != nil {
		in, out := &in.LastEnforcementTime, &out.LastEnforcementTime
		*out = (*in).DeepCopy()
	}
	if in.EnforcedResources != nil {
		in, out := &in.EnforcedResources, &out.EnforcedResources
		*out = make([]EnforcedResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuQuotaStatus.
func (in *GpuQuotaStatus) DeepCopy() *GpuQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(GpuQuotaStatus)
	in.DeepCopyInto(out)
	return out
}
